### ISSUE TITLE
Check geoserver's graphic generation

### ISSUE THREAD

**Issue by rlage** [MinisterioPublicoRJ/inLoco-2.0#144]
Check if and how geoserver can render a graphic image. If it can, which types of graphics it generates? Is it enough for our user's needs?

**Comment by barbier** [comment]
Looks like Geoserver already generate some charts, but on the map by an addon. Maybe we can use the generated XML to add the charts on other areas?

http://geoserver.geo-solutions.it/edu/en/pretty_maps/charting.html
