### ISSUE TITLE
Layer style tooltip

### ISSUE THREAD

**Issue by nighto** [MinisterioPublicoRJ/inLoco-2.0#170]
![image](https://user-images.githubusercontent.com/397851/27878489-c65c4022-6194-11e7-846a-68fe74bcab3c.png)

Tooltips are needed for the layer styles, showing their information (which is shown right now at the menu on inLoco v1):

![image](https://user-images.githubusercontent.com/397851/27878582-1b0b0914-6195-11e7-9943-d23d6f9d9524.png)

We should decide if they open to the left, top or bottom, and if they look like the menu tooltip.

We should refactor the current Tooltip component to be less dependant of SidebarLeft and to take as argument the tooltip direction.

**Comment by lucianobarauna** [comment]
Resolved in : https://github.com/MinisterioPublicoRJ/inLoco-2.0/pull/175

**Comment by lucianobarauna** [comment]
Merge to develop
