### ISSUE TITLE
Legend with max-height for 7 items

### ISSUE THREAD

**Issue by rlage** [MinisterioPublicoRJ/inLoco-2.0#196]
Set the maximum height of legent to fit 7 items

**Comment by rlage** [comment]
Is this to set the size of the container that shows each square that represents a legend? It means that if we have more than 7 squares we will have a scroll on the legend?

For instance:
![image](https://user-images.githubusercontent.com/1390422/28537519-8d2a88da-7081-11e7-8397-37a687ee9319.png)

in the image above, we would only show first 7 items, leaving "acima de 100.000 habitantes" hidden, accessible by scrolling the container?

Question just to clarify the issue.

**Comment by barbier** [comment]
Yes, it's possible if the image is inside some kind of container.
The container element can have the properties to limit the size and the image just go along with it.

**Comment by rlage** [comment]
I know. I know, just wanted to clarify that we will deliberately hide part of the legend.
