### ISSUE TITLE
Hover effect on layer styles

### ISSUE THREAD

**Issue by rlage** [MinisterioPublicoRJ/inLoco-2.0#204]
On sidebar right, on hovering a layer's style, change the title and make a fixed description clearer.

**Comment by lucianobarauna** [comment]
We'll have to look at the plugin to change the inline style it puts on the element. As soon as we're free we see that.

**Comment by rlage** [comment]
This issue is to change the style while hovering a layer's style. It doesn't have anything to do with the drag and drop plugin.

**Comment by lucianobarauna** [comment]
Create issue #226 to solve styles in dragindrop plugin
