### ISSUE TITLE
Layer search component

### ISSUE THREAD

**Issue by rlage** [MinisterioPublicoRJ/inLoco-2.0#23]
Develop a layer search component. As the user writes on the search input, the menu should show only layers that match the search string.

**Comment by barbier** [comment]
On the current application, the search looks for the value into the entire layer object, not only on its name. Will we keep it?

**Comment by rlage** [comment]
I believe it looks for the description and the name, right? I believe @pedromarins could shed a light on this.

**Comment by rlage** [comment]
I believe this was fixed by #46 ?

**Comment by rlage** [comment]
Fixed by #51
