### ISSUE TITLE
Each child should have unique "key" prop

### ISSUE THREAD

**Issue by rlage** [MinisterioPublicoRJ/inLoco-2.0#27]
Each child in an array or iterator should have a unique "key" prop. Check the render method of `Menu`.  See https://fb.me/react-warning-keys for more information.

**Comment by nighto** [comment]
Done on 269219638.

**Comment by rlage** [comment]
Some merge was poorly done. Probably mine. I will refix it and then close it when merged.

**Comment by nighto** [comment]
Yeah. On `Menu.js`, when `item` is a number, `key` can't be `item.idMenu`. Gotta check first before returning directly.

**Comment by rlage** [comment]
@nighto , fixed. Waiting for pull request revision (@pedromarins )
