### ISSUE TITLE
Decide branch naming and commit messages convention

### ISSUE THREAD

**Issue by rlage** [MinisterioPublicoRJ/inLoco-2.0#30]
I believe we have decided on something like:
bug/nameofbug
feature/nameoffeature

but I don't think we've documented it anywhere.

Also, for my latest branch, I named it after the issue I was solving... like branch issue-#27. We should discuss the name convention. I think that it would be nice to track a branch to the issue it is supposed to solve.

**Comment by rlage** [comment]
Updating: I think we should maintain the branch names to something like

feature/name-of-feature 

but we should use " fix #issueNumber " as a commit message, like this: b7cca56f8

**Comment by pedromarins** [comment]
Agreed!

**Comment by nighto** [comment]
Another 2¢:

When you use `issue #xyz` on the commit message, you make a simple reference (appears linked to the issue).
When you use `fix #xyz` it closes the issue automatically when the branch is merged to `develop` branch. (i.e. doesn't close automatically when you push it to the server; you have to wait for the code to be successfully merged to be able to close the issue).

Reference: https://help.github.com/articles/closing-issues-via-commit-messages/
