### ISSUE TITLE
Increase color range for graphics

### ISSUE THREAD

**Issue by rlage** [MinisterioPublicoRJ/inLoco-2.0#342]
In cases where we have 3 or more groups to show, for instance, ethnic groups, like "black, brown, albino, white..." the three color cap hurts the graphics.

**Comment by barbier** [comment]
I'm with a fix for it, but there are some problems.
On the first and second graphics, there are no data to show and on the third there's only one value, maybe Charts is forcing something anyway?
![image](https://user-images.githubusercontent.com/1870079/31090317-a154b2da-a77d-11e7-8053-5231022d6c67.png)

**Comment by rlage** [comment]
I believe that we should check if there is data available to draw the chart. If there isn't, show a message that no data is available.

When there is only one item, the ideal would be a full circle with the color, like the last graphic "lesão corporal seguida de morte (2016)", but without that line in the center. But maybe this is the libs' standard behaviour .
