### ISSUE TITLE
Download (WFS) is not considering viewport

### ISSUE THREAD

**Issue by rlage** [MinisterioPublicoRJ/inLoco-2.0#345]
When using the option to download the visible area as a data file (CSV, KML, XLS or Shapefile) the WFS call is not considering the viewport, downloading data of the whole state.

**Comment by mcastre** [comment]
hello @rlage! Could you provide a bit more info on this issue?

**Comment by rlage** [comment]
Hi @mcastre, we have a download function. If you look to the top right, you’ll see a bunch of icons. One of them is download. The user can choose diferente formats to download. The problem is that the image that is being generated is not considering the viewport, which means that when the user zoom in or zoom out, for example, the image does not reflect the map he/she is currently seeing.

**Comment by mcastre** [comment]
@rlage Could you explain a bit how you guys create the download file of the map? I downloaded the png format and it looks like it just screenshotted the current window. In my opinion, I think you should hide the web controls on print.

**Comment by nighto** [comment]
Sorry for not making the issue clearer @mcastre.

Yes, the image and pdf options are taking a screenshot of the window (and if you could help by hiding the controls it'd be great!).

This issue on the other hand is about the data formats, such as csv, xls, kml and shp, which are not considering the viewport visible.

I'll update the description (and create another one for hiding the controls).
