### ISSUE TITLE
Download as image (jpg/pdf) should not have the controls

### ISSUE THREAD

**Issue by nighto** [MinisterioPublicoRJ/inLoco-2.0#354]
When generating the screenshot to download the map view as an image (jpg/pdf option) we should hide the controls. I think that InLoco logo could remain visible, but all other options should be hidden.

Related to #345
@mcastre

**Comment by mcastre** [comment]
@nighto @rlage heres the PR for this issue! 
https://github.com/MinisterioPublicoRJ/inLoco-2.0/pull/357

**Comment by nighto** [comment]
Awesome! Merging the PR. Thank you! :)

**Comment by mcastre** [comment]
Glad I could help!
