### ISSUE TITLE
Sinalid - Desaparecidos plugin

### ISSUE THREAD

**Issue by nighto** [MinisterioPublicoRJ/inLoco-2.0#397]
Implement a component/plugin to show Sinalid - Desaparecidos content.

http://apps.mprj.mp.br/sistema/sinalid/sinalid.html?deleg=226

**Comment by barbier** [comment]
Should it be on an iframe inside `SidebarRight` component?
Probably should require some CORS to do it, but with a few CSS changes it can reasonably fit there
